Isi 706 anzeige des gewaehlten foerdermix
it-at-m/isi-frontend pull request #127
Opened 2023-10-13 09:27 UTC by DomixD

**Description**

- Der Bug wurde behoben, dass beim initialen Laden kein Fördermix angezeigt wurde. 
- Desweiteren werden nun die Fördermixe primär über den Store geladen
- Der Store FördermixStore wurde zu einem allgemeinen Store in StammdatenStore umbenannt

**Reference**

Issues ISI-706

2023-10-13 12:23 UTC, ghost requested changes

2023-10-13 12:23 UTC, ghost commented on frontend/src/components/bauraten/BaurateComponent.vue
> -        <foerdermix-staemme-drop-down
Der Import und Eintrag bei `@Component` von dieser Komponente ist in der Datei noch drin.

2023-10-13 12:23 UTC, ghost commented on frontend/src/store/modules/StammdatenStore.ts
> +};
Ich finde die Idee von einem Store für Stammdaten gut, doch dann sollte auch die `fileInformation` vom `FileInfoStammStore` hierhin umgezogen werden, oder?

Ich werde aber nicht darauf bestehen, dass du das noch im Rahmen dieser Review machst. Du kannst dafür auch eine eigene Refactoring-User-Story aufmachen.

2023-10-16 06:58 UTC, DomixD commented on frontend/src/store/modules/StammdatenStore.ts
> +};
Gibt es davon irgendwo eine Übersicht was alles so zu den Stammdaten gehört oder was welche sind?

2023-10-16 09:33 UTC, banzuu commented on frontend/src/store/modules/StammdatenStore.ts
> +};
Kenne da keine Übersicht. Habe auf den ersten Blick nur den FileInfoStammStore gefunden.

2023-10-16 09:40 UTC, banzuu approved these changes, later dismissed

2023-10-23 11:40 UTC, boal approved these changes, later dismissed

2023-10-25 09:57 UTC, boal approved these changes

2023-10-25 09:58 UTC, merged