Isi 950 fontend erstellung weitere verfahren abfrageart 03 2
it-at-m/isi-frontend pull request #140
Opened 2023-11-14 10:04 UTC by lhmAschaenz

**Description**

Umsetzung des Frontends ([ISI-950](https://jira.muenchen.de/browse/ISI-950)) der Main Story [ISI-920](https://jira.muenchen.de/browse/ISI-920)

**Reference**

Issues #950

2023-11-14 13:20 UTC, boal requested changes

2023-11-14 13:20 UTC, boal commented on frontend/src/components/abfragen/AbfrageNavigationTree.vue
> +    abfrage.artAbfrage === AbfrageDtoArtAbfrageEnum.Bauleitplanverfahren
Die Verschachtelung ist sehr schwer zu lesen.

Besser wäre hier ein klassisches if-else-Konstrukt.

2023-11-14 13:20 UTC, boal commented on frontend/src/components/abfragen/AbfrageNavigationTree.vue
> +    abfrage.artAbfrage === AbfrageDtoArtAbfrageEnum.Bauleitplanverfahren
Die Verschachtelung ist sehr schwer zu lesen.

Besser wäre hier ein klassisches if-else-Konstrukt.

2023-11-14 13:20 UTC, boal commented on frontend/src/components/abfragen/AbfrageNavigationTree.vue
> +  abfragevariante: AbfragevarianteBauleitplanverfahrenDto | AbfragevarianteBaugenehmigungsverfahrenDto,
Fehlt hier das WeiteresVerfahrenDto?

2023-11-14 13:20 UTC, boal commented on frontend/src/components/abfragen/AbfrageNavigationTree.vue
> +  abfragevariante: AbfragevarianteBauleitplanverfahrenDto | AbfragevarianteBaugenehmigungsverfahrenDto,
Fehlt hier das WeiteresVerfahrenDto?

2023-11-14 13:20 UTC, boal commented on frontend/src/components/abfragen/AbfrageNavigationTree.vue
> +      : AbfrageFormType.BAUGEBIET_BAUGENEHMIGUNGSVERFAHREN;
Fehlt hier die Prüfung auf WEITERES_VERFAHREN

2023-11-14 14:14 UTC, boal requested changes

2023-11-14 14:14 UTC, boal commented on frontend/src/mixins/requests/AbfragenApiRequestMixin.ts
> +      dto.artAbfrage === AbfrageDtoArtAbfrageEnum.Bauleitplanverfahren
Das verschachtelte Statement ist sehr unübersichtlich.

Hier besser ein klassisches If-Else-Konstrukt verwenden.

2023-11-14 14:14 UTC, boal commented on frontend/src/mixins/requests/AbfragenApiRequestMixin.ts
> +      dto.artAbfrage === AbfrageDtoArtAbfrageEnum.Bauleitplanverfahren
Das verschachtelte Statement ist sehr unübersichtlich.

Hier besser ein klassisches If-Else-Konstrukt verwenden.

2023-11-14 14:14 UTC, boal commented on frontend/src/mixins/requests/AbfragenApiRequestMixin.ts
> +      dto.artAbfrage === AbfrageDtoArtAbfrageEnum.Bauleitplanverfahren
Das verschachtelte Statement ist sehr unübersichtlich.

Hier besser ein klassisches If-Else-Konstrukt verwenden.

2023-11-14 14:14 UTC, boal commented on frontend/src/mixins/requests/AbfragenApiRequestMixin.ts
> +        ? (dto as { artAbfrage: "BAULEITPLANVERFAHREN" } & BauleitplanverfahrenInBearbeitungFachreferatDto)
Das verschachtelte Statement ist sehr unübersichtlich.

Hier besser ein klassisches If-Else-Konstrukt verwenden.

2023-11-14 14:14 UTC, boal commented on frontend/src/mixins/validation/ValidatorMixin.ts
> +      abfrage.artAbfrage === AbfrageDtoArtAbfrageEnum.Bauleitplanverfahren
Das verschachtelte Statement ist sehr unübersichtlich.

Hier besser ein klassisches If-Else-Konstrukt verwenden.

2023-11-14 14:14 UTC, boal commented on frontend/src/mixins/validation/ValidatorMixin.ts
> +      abfrage.artAbfrage === AbfrageDtoArtAbfrageEnum.Bauleitplanverfahren
Das verschachtelte Statement ist sehr unübersichtlich.

Hier besser ein klassisches If-Else-Konstrukt verwenden.

2023-11-14 16:10 UTC, lhmAschaenz commented on frontend/src/components/abfragen/AbfrageNavigationTree.vue
> +    abfrage.artAbfrage === AbfrageDtoArtAbfrageEnum.Bauleitplanverfahren
done

2023-11-14 16:10 UTC, lhmAschaenz commented on frontend/src/components/abfragen/AbfrageNavigationTree.vue
> +    abfrage.artAbfrage === AbfrageDtoArtAbfrageEnum.Bauleitplanverfahren
done

2023-11-14 16:11 UTC, lhmAschaenz commented on frontend/src/components/abfragen/AbfrageNavigationTree.vue
> +  abfragevariante: AbfragevarianteBauleitplanverfahrenDto | AbfragevarianteBaugenehmigungsverfahrenDto,
oh ja. Done.

2023-11-14 16:11 UTC, lhmAschaenz commented on frontend/src/components/abfragen/AbfrageNavigationTree.vue
> +  abfragevariante: AbfragevarianteBauleitplanverfahrenDto | AbfragevarianteBaugenehmigungsverfahrenDto,
(rot werde). Done

2023-11-14 16:11 UTC, lhmAschaenz commented on frontend/src/components/abfragen/AbfrageNavigationTree.vue
> +      : AbfrageFormType.BAUGEBIET_BAUGENEHMIGUNGSVERFAHREN;
done

2023-11-14 16:11 UTC, lhmAschaenz commented on frontend/src/mixins/requests/AbfragenApiRequestMixin.ts
> +      dto.artAbfrage === AbfrageDtoArtAbfrageEnum.Bauleitplanverfahren
done

2023-11-14 16:12 UTC, lhmAschaenz commented on frontend/src/mixins/requests/AbfragenApiRequestMixin.ts
> +      dto.artAbfrage === AbfrageDtoArtAbfrageEnum.Bauleitplanverfahren
done

2023-11-14 16:12 UTC, lhmAschaenz commented on frontend/src/mixins/requests/AbfragenApiRequestMixin.ts
> +      dto.artAbfrage === AbfrageDtoArtAbfrageEnum.Bauleitplanverfahren
done

2023-11-14 16:12 UTC, lhmAschaenz commented on frontend/src/mixins/requests/AbfragenApiRequestMixin.ts
> +        ? (dto as { artAbfrage: "BAULEITPLANVERFAHREN" } & BauleitplanverfahrenInBearbeitungFachreferatDto)
done

2023-11-14 16:12 UTC, lhmAschaenz commented on frontend/src/mixins/validation/ValidatorMixin.ts
> +      abfrage.artAbfrage === AbfrageDtoArtAbfrageEnum.Bauleitplanverfahren
done

2023-11-14 16:12 UTC, lhmAschaenz commented on frontend/src/mixins/validation/ValidatorMixin.ts
> +      abfrage.artAbfrage === AbfrageDtoArtAbfrageEnum.Bauleitplanverfahren
done

2023-11-15 06:57 UTC, boal approved these changes, later dismissed

2023-11-15 11:12 UTC, boal approved these changes, later dismissed

2023-11-15 12:51 UTC, boal approved these changes, later dismissed

2023-11-23 15:29 UTC, boal approved these changes

2023-11-23 15:36 UTC, merged