Isi 175 abfragevariante beruecksichtigung der bedarfe
it-at-m/isi-frontend pull request #162
Opened 2024-01-10 14:20 UTC by DomixD

**Description**

Neue Attribute wurden im Feld ``Bedarfsmeldungen der Fachreferate`` bei einer Abfragevariante hinzugefügt.

**Reference**

Issues #ISI-175

2024-01-15 09:06 UTC, boal approved these changes

2024-01-15 09:19 UTC, boal requested changes

2024-01-15 09:19 UTC, boal commented on frontend/src/components/abfragevarianten/BedarfsmeldungFachreferateComponent.vue
> +          <h3>Kindertagesbetreuung</h3>
Evtl umbenennen nach `Ausgelöste Bedarfe Kindertagesbetreuung`

Somit ist eindeutig, dass es sich um ausgelöste Bedarfe handelt.

2024-01-15 09:19 UTC, boal commented on frontend/src/components/abfragevarianten/BedarfsmeldungFachreferateComponent.vue
> +          <h3>Schule</h3>
Evtl umbenennen nach `Ausgelöste Bedarfe Schule`

Somit ist eindeutig, dass es sich um ausgelöste Bedarfe handelt.

2024-01-15 10:33 UTC, DomixD commented on frontend/src/components/abfragevarianten/BedarfsmeldungFachreferateComponent.vue
> +          <h3>Kindertagesbetreuung</h3>
Gibt es sonst noch andere Bedarfe? Laut Akzeptanzkriterium soll nur das eine Wort stehen. Weiß nicht ob es dann nicht zu lange wird als Überschrift für zwei Spalten

2024-01-15 10:33 UTC, DomixD commented on frontend/src/components/abfragevarianten/BedarfsmeldungFachreferateComponent.vue
> +          <h3>Schule</h3>
Gibt es sonst noch andere Bedarfe? Laut Akzeptanzkriterium soll nur das eine Wort stehen. Weiß nicht ob es dann nicht zu lange wird als Überschrift für zwei Spalten

2024-01-15 15:02 UTC, boal approved these changes, later dismissed

2024-01-17 08:36 UTC, boal submitted a review, later dismissed

2024-01-29 14:23 UTC, banzuu approved these changes, later dismissed

2024-02-01 09:27 UTC, TiagoKocevar approved these changes
😎

2024-02-01 09:27 UTC, merged