ISI-1108 Sachbearbeitung kann Bauvorhaben aktualisieren
it-at-m/isi-frontend pull request #169
Opened 2024-01-31 11:45 UTC by TiagoKocevar

**Description**

Die Rolle Sachbearbeitung Plan kann ein Bauvorhaben aktualisieren innerhalb einer Abfrage im Status IN_BEARBEITUNG_SACHBEARBEITUNG.

Abändern des Feldes Bauvorhaben in der Abfrage das nun auch Sachbearbeiter im richtigen Status es editieren können. 

Außerdem die mapping methode aktualisiert.

**Reference**

Issues #1108

2024-01-31 12:29 UTC, boal requested changes

2024-01-31 12:29 UTC, boal commented on frontend/src/views/Abfrage.vue
> +          this.relevanteAbfragevarianteId = dto.relevanteAbfragevariante ?? null;
Was wird hier geändert?

2024-01-31 12:29 UTC, boal commented on frontend/src/views/Abfrage.vue
> +          const relevanteId = result.relevanteAbfragevariante;
Was wird hier geändert?

2024-01-31 13:29 UTC, TiagoKocevar commented on frontend/src/views/Abfrage.vue
> +          this.relevanteAbfragevarianteId = dto.relevanteAbfragevariante ?? null;
Sorry für den Fehler. Diese Änderung kam aus einem anderen Branch und ich weiß nicht wie sich das reingeschlichen hat. Habe es jetzt wieder entfernt

2024-01-31 13:31 UTC, boal submitted a review, later dismissed

2024-02-07 12:44 UTC, banzuu approved these changes

2024-02-07 12:45 UTC, merged