Isi 428 verortung adresseingabe
it-at-m/isi-frontend pull request #17
Opened 2023-02-10 09:29 UTC by lhmAschaenz

**Description**

- Refactoring Adresse als wiederverwendbare Komponente (_AdresseComponent_)
- _AdresseComponent_ um Suche nach Adresse durch Anbindung an MAstER erweitert
- Refactoring Swagger-API: Eigene Verzeichnisstruktur für jede API (Backend, MAstER) getrennt
- betroffene Seiten, die die Adresse verwenden, umgestellt:
   - Abfrage
   - Bauvorhaben
   - Infrastruktureinrichtung
   
**Reference**

Issues #ISI-428-Verortung-Adresseingabe

2023-02-13 10:21 UTC, boal requested changes

2023-02-13 10:21 UTC, boal commented on frontend/src/components/common/AdresseComponent.vue
> +                  <v-list-item-title> Keine Suchvorschläge... </v-list-item-title>
Wann erscheint die Meldung `Keine Suchvorschläge...`.

Macht dies Sinn?

Falls keine Suchvorschläge aufgefunden werden, dann wird die Eingabe als `Allgemeine Ortsangabe` gehandhabt.

2023-02-13 10:21 UTC, boal commented on frontend/src/components/common/AdresseComponent.vue
> +            <v-autocomplete
Aktuell werden die Adressdaten als Addresse oder Allgemeine Ortsangabe übernommen, sobald auf die Tabtaste gedrückt wird.

Beim Testen habe ich intuitiv auch auf Enter gedrückt. Hier hat keine Adressdatenübernahme stattgefunden.

Ein Tatendruck auf `Enter` sollte meiner Meinung nach auch eine Adressdatenübernahme auslösen.

2023-02-13 11:10 UTC, lhmAschaenz commented on frontend/src/components/common/AdresseComponent.vue
> +                  <v-list-item-title> Keine Suchvorschläge... </v-list-item-title>
es war als "optional" vorgesehen und dahingehend auch kommentiert, falls im Review der Wunsch geäußert worden wäre, dass man eine Meldung sehen möchte, dann wäre die Implementierung schon da gewesen.

Ich habe den Code dahingehend gelöscht / bereinigt.

2023-02-13 11:25 UTC, lhmAschaenz commented on frontend/src/components/common/AdresseComponent.vue
> +            <v-autocomplete
erledigt

2023-02-13 13:14 UTC, boal approved these changes, later dismissed

2023-02-15 11:37 UTC, boal approved these changes, later dismissed

2023-02-15 15:31 UTC, boal approved these changes, later dismissed

2023-02-15 16:11 UTC, boal approved these changes

2023-02-15 16:12 UTC, merged