ISI-1233 Zeichenlimit für Kommentarfelder
it-at-m/isi-frontend pull request #174
Opened 2024-02-19 07:23 UTC by boal

**Description**

siehe Titel

**Reference**

ISI-1233

2024-02-23 14:01 UTC, Roternando commented
ich bin mir nicht sicher ob das ins frontend oder ins backend muss, also schreibe ich es jetzt mal bei beiden rein:
in die "Freie Eingabe" Felder passen 1000 zeichen rein und man kann speichern, aber die Felder werden nicht größer bzw. passen sich nicht an die steigende zeichenanzahl an. wollte das angemerkt haben falls es wichtig sein sollte.

2024-02-27 11:09 UTC, TiagoKocevar requested changes

2024-02-27 11:09 UTC, TiagoKocevar commented on frontend/src/components/abfragen/baugenehmigungsverfahren/AllgemeineInformationenZurAbfrageBaugenehmigungsverfahrenComponent.vue
>            rows="3"
Könntest du hier rows="3" zu rows="1" abändern. 

Nach den Verbesserungsvorschlägen die im Daily genannt wurden eine gute Entscheidung.

Außerdem wurde das schon im Feld "Hinweise zur Versorgung der Bedarfe außerhalb des Verfahrens" in der BedarfsmeldungComponent.vue (Zeile: 111) gemacht.

2024-02-27 11:09 UTC, TiagoKocevar commented on frontend/src/components/abfragen/bauleitplanverfahren/AllgemeineInformationenZurAbfrageBauleitplanverfahrenComponent.vue
>            rows="3"
Könntest du hier ebenfalls rows="3" zu rows="1" abändern.

2024-02-27 11:09 UTC, TiagoKocevar commented on frontend/src/components/abfragen/weiteresVerfahren/AllgemeineInformationenZurAbfrageWeiteresVerfahrenComponent.vue
>            rows="3"
Könntest du hier ebenfalls rows="3" zu rows="1" abändern.

2024-02-27 11:09 UTC, TiagoKocevar commented on frontend/src/components/abfragevarianten/SachbearbeitungComponent.vue
>              rows="3"
Könntest du hier ebenfalls rows="3" zu rows="1" abändern.

2024-02-27 11:09 UTC, TiagoKocevar commented on frontend/src/components/common/YesNoDialog.vue
> +        maxlength="1000"
Hier die Max Length auf 255 lassen. Das geht darum das der Nutzer bei diesem Feld nur einen kurzen Kommentar setzen will bei einem Statusübergang. 

Außerdem überprüft das Backend die Zeichenlänge bei diesem YesNoDialog.vue:

isi-backend/src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java:throwStringLengthExceededExceptionWhenAnmerkungExceedsLength


```java
 /**
     * Überprüft, ob die Länge einer Anmerkung die maximale Grenze überschreitet
     *
     * @param id        vom Typ {@link UUID} um die Abfrage zu finden
     * @param anmerkung die zur Abfrage hinzugefügt werden soll.
     * @throws StringLengthExceededException Wenn die Anmerkung die maximale Länge von 255 Zeichen überschreitet.
     * @throws EntityNotFoundException       Wenn die Abfrage nicht gefunden wird.
     */
    private void throwStringLengthExceededExceptionWhenAnmerkungExceedsLength(UUID id, String anmerkung)
        throws StringLengthExceededException, EntityNotFoundException, UserRoleNotAllowedException {
        var abfrage = this.abfrageService.getById(id);
        if (!anmerkung.isEmpty()) {
            if (abfrage.getAnmerkung() == null) {
                abfrage.setAnmerkung(anmerkung);
            } else {
                abfrage.setAnmerkung(abfrage.getAnmerkung().concat("\n").concat(anmerkung));
            }

            if (abfrage.getAnmerkung().length() > 255) {
                throw new StringLengthExceededException("Es sind maximal 255 Zeichen erlaubt");
            }
        }
    }
```

2024-02-27 12:21 UTC, TiagoKocevar submitted a review, later dismissed
👍🏽

2024-03-12 15:08 UTC, TiagoKocevar approved these changes
🙋🏽‍♂️

2024-03-12 15:10 UTC, merged