ISI-837 Auslösen von Sobon Berechnung und Auswahl des Sobon wichtigem Fördermix
it-at-m/isi-frontend pull request #181
Opened 2024-03-01 16:09 UTC by TiagoKocevar

**Description**

Checkbox Feld hinzugefügt um anzukreuzen ob es eine Sobon Berechnung geben soll oder nicht. 
V-Select Feld hinzugefügt um die Fördermixe für die Sobon Berechnung auszuwählen.

Außerdem Validation erweitert die überprüft ob der Nutzer alle Felder ausgefüllt hat um eine Sobon Berechnung durchzuführen

**Reference**

Issues #837

2024-03-12 11:00 UTC, boal requested changes

2024-03-12 11:00 UTC, boal commented on frontend/src/components/abfragevarianten/SachbearbeitungComponent.vue
> +            @change="onIsASobonBerechnungChange"
Was bedeutet "onIsASobonBerechnungChange"? Evtl sobonBerechnungChanged oder ähnlich

2024-03-12 11:00 UTC, boal commented on frontend/src/components/abfragevarianten/SachbearbeitungComponent.vue
> +  groupItemsToHeader(foerdermixStaemme: FoerdermixStammModel[]): GroupedStammdaten {
Handelt es sich um die selbe Logik wie im Fördermixformular? Falls ja, sollte diese Methode in eine eigene Klasse ausgelagert werden.

2024-03-12 11:00 UTC, boal commented on frontend/src/components/abfragevarianten/SachbearbeitungComponent.vue
> +            v-model="abfragevarianteSachbearbeitung.isASobonBerechnung"
Soll die sobonursächliche Berechnung durchgeführt werden wenn dieses Attribut auf false ist? 

Falls diese nicht durchgeführt werden soll dies implementiert oder zumindest in einer eigenen Userstory festgehalten werden.

2024-03-12 11:00 UTC, boal commented on frontend/src/components/abfragevarianten/SachbearbeitungComponent.vue
> +      this.abfragevarianteSachbearbeitung?.artAbfragevariante ===
Die Prüfung der If-Bedingung und der Boolsche-Ausdruck innerhalb des If-Statements kann zu einem verundeten boolschen Ausdruck verbunden werden.


```java

return (
      this.abfragevarianteSachbearbeitung?.artAbfragevariante ===
       AbfragevarianteBauleitplanverfahrenDtoArtAbfragevarianteEnum.Bauleitplanverfahren ||
      this.abfragevarianteSachbearbeitung?.artAbfragevariante ===
        AbfragevarianteBauleitplanverfahrenDtoArtAbfragevarianteEnum.WeiteresVerfahren
    ) && 
        abfrage.sobonRelevant === UncertainBoolean.True &&
        (this.abfragevarianteSachbearbeitung?.isASobonBerechnung as boolean) &&
        !_.isNil(this.abfragevarianteSachbearbeitung?.sobonFoerdermix) &&
        !_.isNil(this.abfragevarianteSachbearbeitung?.gfWohnenSobonUrsaechlich)
        
```

2024-03-12 13:40 UTC, TiagoKocevar commented on frontend/src/components/abfragevarianten/SachbearbeitungComponent.vue
> +            v-model="abfragevarianteSachbearbeitung.isASobonBerechnung"
Nein die Sobon Berechnung soll nur durchgeführt werden wenn dieses Attribut true ist.

2024-03-13 10:18 UTC, boal requested changes

2024-03-13 10:18 UTC, boal commented on frontend/src/components/abfragevarianten/SobonBerechnung.vue
> +  }
Leerzeichen zwischen Methoden

2024-03-13 10:18 UTC, boal commented on frontend/src/mixins/validation/ValidatorMixin.ts
> +          return "Die Abfrage muss als SoBoN Relevant markiert werden um eine SoBoN-Berechnung durchzuführen.";
Typo: `SoBoN Relevant` -> `SoBoN-Relevant`

2024-03-13 10:18 UTC, boal commented on frontend/src/utils/MapperUtil.ts
> +/**
Leerzeile zwischen den Methoden.

2024-03-13 12:21 UTC, boal approved these changes, later dismissed

2024-03-15 11:32 UTC, boal approved these changes

2024-03-18 08:12 UTC, merged