Isi 203 schuelerpotentialprognose hochladen
it-at-m/isi-frontend pull request #186
Opened 2024-03-19 10:33 UTC by DomixD

**Description**

In der Abfragevariante  im Rahmen "Bauratendatei und Schülerpotentialprognose" können nun Dokumente hochgeladen werden.

**Reference**

Issues ISI-203

2024-03-19 15:00 UTC, boal requested changes

2024-03-19 15:00 UTC, boal commented on frontend/src/components/abfragevarianten/SachbearbeitungComponent.vue
> +  private schülerpotentialprognoseTitle = "Bauratendatei und Schülerpotentialprognose";
Keine Umlaute `schüler...` im Code.

2024-03-20 08:30 UTC, DomixD commented on frontend/src/components/abfragevarianten/SachbearbeitungComponent.vue
> +  private schülerpotentialprognoseTitle = "Bauratendatei und Schülerpotentialprognose";
Ups dachte eigentlich ich hätte das ohne Umlaute geschrieben^^

2024-03-20 09:24 UTC, boal submitted a review, later dismissed

2024-03-26 10:39 UTC, boal submitted a review, later dismissed

2024-04-09 10:41 UTC, boal approved these changes

2024-04-09 12:10 UTC, merged