Isi 429 ablegegen und anzeigen nutzerinformationen
it-at-m/isi-frontend pull request #19
Opened 2023-02-10 14:48 UTC by TiagoKocevar

**Description**

Implementierung eines V-Menus welches Vor- und Nachname, Abteilung und Rolle  des Nutzers anzeigt. 

Die geholten Daten werden dann im Store abgespeichert

**Reference**

Issues #429

2023-02-13 09:27 UTC, boal requested changes

2023-02-13 09:27 UTC, boal commented on frontend/src/App.vue
> +            <v-card style="max-width: 400px">
Anstelle einer festen Pixelbreite ist denke ich ein Prozentwert besser.

2023-02-13 09:27 UTC, boal commented on frontend/src/App.vue
> +  private fav = true;
Die Variablen `fav`, `message` und `hints` werden im Code nirgends benötigt.

2023-02-13 09:27 UTC, boal commented on frontend/src/App.vue
> +  private menu = false;
Den Datentyp für die Variable `menu` definieren. In Klassen und Komponenten zwischen den Variablen immer eine Zeile abstand.

2023-02-13 09:27 UTC, boal commented on frontend/src/mixins/requests/UserInfoApiRequestMixin.ts
> +    userinfo.role = this.isNotUndefinedOrNull(json.resource_access.isi.roles[0])
Da ein Nutzer mehrere Rollen haben kann, sollten alle Rollen angezeigt werden.

2023-02-13 09:27 UTC, boal commented on frontend/src/types/common/Userinfo.ts
> +  role: string | undefined;
Da ein Nutzer mehrere Rollen haben kann, sollten alle Rollen angezeigt werden. Besser einen Array an String verwenden.

Der Userinfo-Endpunkt antwortet mit einem Array an Rollen.

2023-02-13 09:27 UTC, boal commented on frontend/src/mixins/requests/UserInfoApiRequestMixin.ts
> +        throw this.handleError(true, error);
Da die Daten in der Komponente `App.vue` initial geholt werden, muss die Fehlermeldung als Toast angezeigt werden.

Zusätzlich Testen ob und wie die Fehlermeldung angezeigt wird, da das Backend mit einer fest definierten Art von Fehler antwortet.

Der Keycloak wird definitiv anders bzw. mit einer anderen Fehlerresponse im Body regaieren. Evtl sogar `throw this.handleError(true, error);` durch einen allgemeinen Toast ersetzen (z.B. Nutzerinformationen konnten nicht gelade nwerden).

2023-02-13 09:27 UTC, boal commented on frontend/src/store/modules/SearchStore.ts
> +import { Userinfo } from "@/types/common/Userinfo";
Der Searchstore hat eine andere fachliche Funktion.

Besser ist es einen eigenen Store für die Userinformationen anzulegen.

In Zukunft werden im UserInfoStore sicher mehr Daten hineinkommen.

2023-02-13 09:59 UTC, boal requested changes

2023-02-13 09:59 UTC, boal commented on frontend/src/mixins/requests/UserInfoApiRequestMixin.ts
> +    const userinfo: Userinfo = await fetch(fetchServicesUrl, RequestUtils.getGETConfig())
Was soll angezeigt werden ,wenn der Request fehlschlägt? Also wenn die Anwendung im Modus `no-securty` betrieben wird und der Request an den sso keinen Access-Token beinhaltet?

2023-02-13 10:27 UTC, TiagoKocevar commented on frontend/src/App.vue
> +  private menu = false;
Wenn ich den Datentyp boolean angebe meckert eslint (Type boolean trivially inferred from a boolean literal, remove type annotation.)

2023-02-13 12:30 UTC, boal submitted a review, later dismissed

2023-02-13 12:30 UTC, boal commented on frontend/src/App.vue
> +      userRoles += role + ", ";
Für die Konkatenierung kannst du Lodash `join` verwenden.

https://lodash.com/docs/4.17.15#join

2023-02-13 15:26 UTC, banzuu commented on frontend/src/App.vue
> +              </v-list>
Brauchst du die v-list, wenn du eh nur ein einziges Item hast?

2023-02-13 16:01 UTC, banzuu submitted a review, later dismissed

2023-03-03 11:37 UTC, DomixD approved these changes

2023-03-03 11:38 UTC, merged