ISI-1465-Leere-Fehlermeldung
it-at-m/isi-frontend pull request #208
Opened 2024-04-16 10:36 UTC by lhmAschaenz

**Description**

Validierung erweitert: Für jedes Dokument muss eine Dokumentenart angegeben sein

Closes 
#ISI-1465

2024-04-17 06:44 UTC, boal requested changes

2024-04-17 06:44 UTC, boal commented on frontend/src/mixins/validation/ValidatorMixin.ts
> +  public findFaultInDokumente(dokumente: Array<DokumentDto> | undefined): string | null {
Dokumente sind in der Anwendung auch an anderen Stellen vorhanden. Diese sollten dort auch validiert werden.

- `Bauratendatei und Schülerpotentialprognose` in Abfragevariante
- Bauvorhaben
- In der Kommentarkomponente

2024-04-17 09:22 UTC, lhmAschaenz commented on frontend/src/mixins/validation/ValidatorMixin.ts
> +  public findFaultInDokumente(dokumente: Array<DokumentDto> | undefined): string | null {
umgesetzt

2024-04-17 09:25 UTC, boal submitted a review, later dismissed

2024-04-22 06:39 UTC, boal approved these changes

2024-04-22 06:59 UTC, merged