Isi 474 auto statusuebergaenge
it-at-m/isi-frontend pull request #22
Opened 2023-02-21 09:35 UTC by TiagoKocevar

**Description**

Feld auf nicht readonly gesetzt und den Pfeil beim V-Select enfternt. Habe es als V-Select gelassen da aus den Lookup Listen die Anzeige Werte geholt werden

**Reference**

Issues #374

2023-02-24 07:35 UTC, boal requested changes

2023-02-24 07:35 UTC, boal commented on frontend/src/components/abfragen/AbfrageComponent.vue
>              <template #label>
Meiner Meinung nach kann beim Status das Sternchen für ein Pflichtfeld weg, da der Status nicht über eine Eingabe gepflegt wird, sondern immer gesetzt ist.

2023-02-24 08:24 UTC, boal approved these changes, later dismissed

2023-02-24 09:39 UTC, boal approved these changes

2023-03-08 09:27 UTC, TiagoKocevar commented
Diese Pull Request wird geschlossen da der Branch von ISI-474 denn Zustandsautomaten schon gemerged hat

2023-03-08 09:27 UTC, closed without merging