ISI-569 Fördermix für alle Bauraten setzen
it-at-m/isi-frontend pull request #233
Opened 2024-06-26 09:39 UTC by TiagoKocevar

**Description**

Der Fördermix kann nun per Button für alle Bauraten einer Abfragevariante gesetzt werden.

**Reference**

Issues #XXX

2024-06-26 09:49 UTC, banzuu approved these changes, later dismissed

2024-07-02 08:59 UTC, banzuu requested changes

2024-07-02 08:59 UTC, banzuu commented on frontend/src/views/Abfrage.vue
> +
`console.log` bitte entfernen.

2024-07-02 09:01 UTC, banzuu approved these changes, later dismissed

2024-07-03 12:03 UTC, boal approved these changes, later dismissed

2024-07-03 12:36 UTC, boal approved these changes

2024-07-03 12:59 UTC, merged