Isi 436 update gs nachmittagsbetreuung
it-at-m/isi-frontend pull request #28
Opened 2023-03-01 07:14 UTC by DomixD

**Description**

Folgende Felder wurden ergänzt: anzahlHortPlaetze, anzahlHortGruppen und wohnungsnaheHortPlaetze

**Reference**

Issues ISI-436

2023-03-02 06:49 UTC, boal requested changes

2023-03-02 06:49 UTC, boal commented on frontend/src/components/infrastruktureinrichtung/GsNachmittagBetreuungComponent.vue
> +            label="Anzahl der Hortplätze"
Pflichtfelder mit einem gelben Stern im Text kennzeichnen.

![image](https://user-images.githubusercontent.com/56300801/222351417-5ea1d932-8062-4479-ad2b-1c721c53f8f1.png)

2023-03-02 06:49 UTC, boal commented on frontend/src/components/infrastruktureinrichtung/GsNachmittagBetreuungComponent.vue
> +            label="Anzahl der Hortgruppen"
Pflichtfelder mit einem gelben Stern im Text kennzeichnen.

![image](https://user-images.githubusercontent.com/56300801/222351417-5ea1d932-8062-4479-ad2b-1c721c53f8f1.png)

2023-03-02 06:49 UTC, boal commented on frontend/src/components/infrastruktureinrichtung/GsNachmittagBetreuungComponent.vue
> +            label="Anzahl der Hortgruppen"
Validierung der Eingabefelder mit  >=0.

Somit können keine negativen Werte vergeben werden.

2023-03-02 06:49 UTC, boal commented on frontend/src/components/infrastruktureinrichtung/GsNachmittagBetreuungComponent.vue
> +            label="Anzahl der Hortplätze"
Validierung der Eingabefelder mit  >=0.

Somit können keine negativen Werte vergeben werden.

2023-03-02 06:49 UTC, boal commented on frontend/src/components/infrastruktureinrichtung/GsNachmittagBetreuungComponent.vue
> +            label="Anzahl der wohnungsnahen Hortplätze"
Validierung der Eingabefelder mit  >=0.

Somit können keine negativen Werte vergeben werden.

2023-03-03 08:10 UTC, DomixD commented on frontend/src/components/infrastruktureinrichtung/GsNachmittagBetreuungComponent.vue
> +            label="Anzahl der Hortplätze"
Das wird schon durch die Componente `num-field` abgedeckt

2023-03-03 08:11 UTC, DomixD commented on frontend/src/components/infrastruktureinrichtung/GsNachmittagBetreuungComponent.vue
> +            label="Anzahl der Hortgruppen"
Das wird schon durch die Componente `num-field` abgedeckt

2023-03-03 08:11 UTC, DomixD commented on frontend/src/components/infrastruktureinrichtung/GsNachmittagBetreuungComponent.vue
> +            label="Anzahl der Hortgruppen"
Das wird schon durch die Componente `num-field` abgedeckt

2023-03-03 08:11 UTC, DomixD commented on frontend/src/components/infrastruktureinrichtung/GsNachmittagBetreuungComponent.vue
> +            label="Anzahl der Hortplätze"
Das wird schon durch die Componente `num-field` abgedeckt

2023-03-03 08:11 UTC, DomixD commented on frontend/src/components/infrastruktureinrichtung/GsNachmittagBetreuungComponent.vue
> +            label="Anzahl der wohnungsnahen Hortplätze"
Das wird schon durch die Componente `num-field` abgedeckt

2023-03-03 08:34 UTC, boal commented on frontend/src/components/infrastruktureinrichtung/GsNachmittagBetreuungComponent.vue
> +            label="Anzahl der Hortplätze"
achso

2023-03-03 08:34 UTC, boal approved these changes, later dismissed

2023-03-06 07:06 UTC, boal approved these changes

2023-03-06 07:15 UTC, merged