Isi 493 fix bauvorhaben aktualisieren
it-at-m/isi-frontend pull request #31
Opened 2023-03-10 09:40 UTC by TiagoKocevar

**Description**

Bauvorhaben konnte nicht mehrmals hintereinander aktualisiert werden. 

Habe es gefixt in dem ich das zurückgegebene Bauvorhaben im Store speichere und mit einem Watcher auf änderung auf den Store schaue. Sobald eine Änderung erkannt wurde wird das neue Objekt im Frontend angezeigt 

**Reference**

Issues #493

2023-03-10 10:48 UTC, boal requested changes

2023-03-10 10:48 UTC, boal commented on frontend/src/views/Bauvorhaben.vue
> +
Unnötige Leerzeichen entfernen.

2023-03-10 10:50 UTC, boal submitted a review, later dismissed

2023-03-20 10:37 UTC, DomixD approved these changes

2023-03-20 10:39 UTC, merged