ISI-480 Statuswechsel in einer Infrastrukturabfrage
it-at-m/isi-frontend pull request #38
Opened 2023-04-03 07:53 UTC by TiagoKocevar

**Description**

Statusübergang Buttons werden nun dynamisch angezeigt abhängig was der Transitions Endpunt im Backend zurückgibt.

Bei der Transition "IN BEARBEITUNG SETZEN" gibt es eine ausnahme weil dort der Nutzer nicht die Abfrage verlassen will sondern direkt weiter arbeiten möchte.

**Reference**

Issues #480

2023-04-03 14:11 UTC, boal requested changes

2023-04-03 14:11 UTC, boal commented on frontend/src/mixins/requests/StatusUebergangApiRequestMixin.ts
> +        Toaster.toast(`Beim ${transition.buttonName} ist ein Fehler aufgetreten`, Levels.ERROR);
Errorhandling analog zu den anderen Mixins.

```ts
.catch((error) => {
        throw this.handleError(showInInformationList, error);
      });

```

2023-04-03 14:11 UTC, boal commented on frontend/src/mixins/requests/StatusUebergangApiRequestMixin.ts
> +        if (response.status == 200) {
Alternativ `if (response.ok) {`. Deckt die Statuscodes 200-299 ab.

2023-04-03 14:11 UTC, boal commented on frontend/src/views/Abfrage.vue
> +      const response = await this.statusUebergangRequest(transition, this.abfrageId);
Es handelt sich nicht um die Response sondern um einen Boolean ob der Statusübergang erfolgreich war.

2023-04-04 12:20 UTC, banzuu commented on frontend/src/views/Abfrage.vue
>            id="abfrage_yes_no_dialog_freigeben"
Die `id` muss noch angepasst werden.

2023-04-04 12:20 UTC, banzuu commented on frontend/src/views/Abfrage.vue
> +        if (!(transition.buttonName === "IN BEARBEITUNG SETZEN")) {
Es ist unpraktisch, nach einem statischen String abzufragen (z.B. wenn sich der Wert in der Zukunft ändert).

Du kannst im Backend bei den `StatusAbfrageEvents` die Annotation `@Schema(enumAsRef = true)` setzen, damit das Enum als API-Klasse generiert wird, siehe auch [hier](https://github.com/it-at-m/isi-backend/blob/ISI-480-Statuswechsel-in-einer-Infrastrukturabfrage/src/main/java/de/muenchen/isi/infrastructure/entity/enums/lookup/UncertainBoolean.java#L11).

2023-04-04 14:15 UTC, banzuu approved these changes, later dismissed

2023-04-21 11:26 UTC, banzuu submitted a review, later dismissed

2023-04-27 09:12 UTC, boal requested changes

2023-04-27 09:12 UTC, boal commented on frontend/src/mixins/requests/StatusUebergangApiRequestMixin.ts
> +  async statusUebergangRequest(transition: TransitionDto, abfrageId: string | undefined): Promise<boolean> {
Leerzeilen zwischen  Klassendefinition und Methode.

2023-04-27 09:12 UTC, boal commented on frontend/src/mixins/requests/StatusUebergangApiRequestMixin.ts
> +    await fetch(fetchUrl, RequestUtils.getPUTConfig())
Das fetch und die Behandlung lässt sich vereinfachen. Somit kann auch die Variable `successFullRequest ` entfallen.

```ts
    return fetch(fetchUrl, RequestUtils.getPUTConfig())
      .then((response) => response.ok)
      .catch((error) => {
        this.handleError(true, error);
        return false;
      });
```

2023-04-27 09:12 UTC, boal commented on frontend/src/views/Abfrage.vue
> +          this.getAbfrageById();
Die Methode `getAbfrageById` umbennnen. Da keine Abfrage zurückgegeben wird.

Die Methode setzt die im Parameter ID referenzierte Abfrage in den Store. -> Evtl. `setSelectedAbfrageInStore` oder ähnlich.

2023-04-27 09:12 UTC, boal commented on frontend/src/views/Abfrage.vue
> +  private saveAbfrageInStore(abfrage: InfrastrukturabfrageModel) {
Diese Methode immer zum Setzen eines Abfragemodels verwenden.

Zum Beispiel die Methode `getAbfrageById` setzt die slectedAbfragemehrmals im Store. Darin kann die Methode `saveAbfrageInStore` für jeden Storecommit verwendet werden.

2023-04-27 09:13 UTC, boal requested changes

2023-04-27 09:13 UTC, boal commented on frontend/src/api/api-client/isi-backend/models/AbfrageDto.ts
> +import {
Merge Conflicte auflösen.

2023-04-27 11:54 UTC, boal requested changes

2023-04-27 11:54 UTC, boal commented on frontend/src/views/Abfrage.vue
>          .then((dto) => {
Alle `this.$store.commit("search/selectedAbfrage", XXX)` in dieser Methode können durch due Methode `saveAbfrageInStore` ersetzt werden.

2023-04-27 14:47 UTC, boal approved these changes

2023-04-28 07:22 UTC, merged