510✨ Abfragevariante Name hinzugefügt
it-at-m/isi-frontend pull request #40
Opened 2023-04-03 13:33 UTC by TiagoKocevar

**Description**

Abfragevarianten Feld hinzugefügt 

**Reference**

Issues #510

2023-04-04 07:45 UTC, boal requested changes

2023-04-04 07:45 UTC, boal commented on frontend/src/mixins/validation/ValidatorMixin.ts
> +      return "Bitte geben Sie einen Abfragevarianten Name an";
Text anders Formulieren:

`Bitte geben Sie einen Abfragevarianten Name an` -> `Bitte geben Sie einen Namen für die Abfragevariante an.`

2023-04-04 11:48 UTC, banzuu approved these changes, later dismissed

2023-04-06 12:15 UTC, boal approved these changes

2023-04-12 05:57 UTC, merged