ISI-45/ISI-555 Abfragevariante Relevant markieren und Bug Fix
it-at-m/isi-frontend pull request #63
Opened 2023-05-31 11:06 UTC by TiagoKocevar

**Description**

In dieser Story habe ich das Feature implementiert Abfragevarianten als Relevant zu markieren. Dies geschieht über die Abfrageservice Klasse. 

Ich habe auch noch 3 neue Klassen hinzugefügt die wir in Zukunft noch gebrauchen werden aber mit der Story nicht viel zu tun haben. Es geht um die Klassen AbfrageerstellungInfrastrukturabfrageAngelegt, AbfrageerstellungAbfragevarainteAngelegt, AbfrageerstellungAbfrageAngelegt. Diese haben alle Attribute die der Abfrageersteller editieren darf im Status ANGELEGT. 

In Zukunft wird es abhängig von der Rolle und dem Status noch weitere Klassen dieser Art geben. Dies habe ich abgesprochen mit Albrecht und Boxi. 

Außerdem habe ich den Bug gefixt mit den nicht funktionierenden Statusänderungen dies geschieht dadurch das ich das Speichern bevor ein Statusübergang passiert entfernt habe da der aktuelle PATCH nur im Status ANGELEGT und mit der Rolle Abfrageersteller funktioniert. 

Habe dafür denn Button im Frontend abgeändert das man nur noch eine Statusänderung durchführen kann wenn alles gespeichert wurde. 

**Reference**

Issues ISI-45, ISI-555

2023-06-02 10:47 UTC, boal requested changes

2023-06-02 10:47 UTC, boal commented on frontend/src/api/json/DO280 03.07.2023 Garching.ics
> +BEGIN:VCALENDAR
Ich glaube das kannst du Löschen! :-)

2023-06-02 10:47 UTC, boal commented on frontend/src/components/abfragen/AbfrageNavigationTree.vue
> +  private relevantAbfragevariante(selectedAbfrageTreeItem: AbfrageTreeItem): AbfrageTreeItem {
Das Event so nennen was es eigentlich bedeuten oder machen soll.

z.B. `markAbfragevarianteAsRelevant`

2023-06-02 10:47 UTC, boal commented on frontend/src/mixins/security/AbfrageSecurityMixin.ts
> +          abfrage.abfrage.statusAbfrage === StatusAbfrage.InBearbeitungSachbearbeitung
Warum entfällt die Prüfung auf Status OFFEN?

2023-06-02 10:47 UTC, boal commented on frontend/src/mixins/validation/ValidatorMixin.ts
> +    let counter = 0;
Counter umbennen. Also was dieser Zählt.

`couterRelevantAbfragevarianten`

2023-06-02 10:47 UTC, boal commented on frontend/src/utils/MapperUtil.ts
> +  const abfragevarianten = [] as AbfrageerstellungAbfragevarianteAngelegtDto[];
Schade das es für Javascript/Typescript keine generierbaren Mapper ananlog der Java-Lib Mapstruct gibt!

2023-06-02 10:47 UTC, boal commented on frontend/src/utils/MapperUtil.ts
> +  infrastrukturabfrageDto.abfragevarianten?.forEach((abfragevariante) => {
Anstelle `forEach` und dem Anfügen an den Array für jeden ForEach-Durchlauf kann die Methode `map` verwendet werden.

```ts
const abfragevarianten = infrastrukturabfrageDto.abfragevarianten?.forEach((abfragevariante) => {
{
      id: abfragevariante.id,
      version: abfragevariante.version,
      abfragevariantenName: abfragevariante.abfragevariantenName as string,
      abfragevariantenNr: abfragevariante.abfragevariantenNr as number,
      ...
      abfragevariante.geschossflaecheWohnenBestandswohnbaurecht,
      geschossflaecheWohnenFestgesetzt: abfragevariante.geschossflaecheWohnenFestgesetzt,
      geschossflaecheWohnenGenehmigt: abfragevariante.geschossflaecheWohnenGenehmigt,
      geschossflaecheWohnenSoBoNursaechlich: abfragevariante.geschossflaecheWohnenSoBoNursaechlich,
    } as AbfrageerstellungAbfragevarianteAngelegtDto;
}

```

2023-06-02 10:47 UTC, boal commented on frontend/src/views/Abfrage.vue
> +        Toaster.toast("Relevante Abfragevariante wurde erfolgreich geändert", Levels.SUCCESS);
Text evtl. umbennnen. -> `Abfragevariante <DER_NAME> in Abfrage <DER_NAME> als relevant markiert.`

2023-06-02 10:47 UTC, boal commented on frontend/src/views/Abfrage.vue
> +        "Um die Abfragevariante Relevant zu markieren Abfragevariante erstmal abspeichern"
Evtl. umbennen -> `Vor relevantsetzung einer Abfrage ist diese zu speichern.` oder so ähnlich.

2023-06-02 11:06 UTC, TiagoKocevar commented on frontend/src/api/json/DO280 03.07.2023 Garching.ics
> +BEGIN:VCALENDAR
Hahaha das habe ich gerade null erwartet

2023-06-02 11:10 UTC, TiagoKocevar commented on frontend/src/mixins/security/AbfrageSecurityMixin.ts
> +          abfrage.abfrage.statusAbfrage === StatusAbfrage.InBearbeitungSachbearbeitung
Was darf denn der Sachbearbeiter editieren im Status OFFEN dachte immer er darf nur beim Status IN_BEARBEITUNG_SACHBEARBEITUNG etwas hinzufügen oder editieren. Deswegen auch der Button IN BEARBEITUNG SETZTEN

2023-06-02 11:13 UTC, TiagoKocevar commented on frontend/src/utils/MapperUtil.ts
> +  const abfragevarianten = [] as AbfrageerstellungAbfragevarianteAngelegtDto[];
Ich habe nachgeschaut es gibt eine Libary aber das würde kompliziert werden mit den generierten Klassen deswege musste ich den Selberschreiben. 

Ist wirklich Schade weil es wirklich sehr nervig ist so einen Mapper zu schreiben

2023-06-02 11:19 UTC, TiagoKocevar commented on frontend/src/views/Abfrage.vue
> +        Toaster.toast("Relevante Abfragevariante wurde erfolgreich geändert", Levels.SUCCESS);
`Abfragevariante ${this.selectedAbfragevariante.id} in Abfrage ${this.abfrageWrapped.infrastrukturabfrage.displayName} hat ihren Relevanten Status geändert.`

Habe Status geändert geschrieben da er ja auch eine Relevante Abfragevariante abwählen kann und dann die falsche Meldung stehen würde

2023-06-05 11:13 UTC, banzuu submitted a review, later dismissed

2023-06-05 11:26 UTC, boal approved these changes, later dismissed

2023-06-07 07:59 UTC, boal approved these changes

2023-06-07 07:59 UTC, boal approved these changes

2023-06-07 08:00 UTC, merged